import { Project } from "./types";

export const PROJECTS: readonly Project[] = [
  {
    slug: "find-my-item",
    title: "찾아줘!",
    summary: "지도 기반 분실물 등록 · 실시간 채팅으로 되찾는 서비스",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "React Query",
      "Axios",
      "Jest",
      "React Testing Library",
      "Playwright",
    ],
    thumbnail: { src: "/projects/find-my-item.ico", alt: "찾아줘 이미지" },
    period: "2025.09 - 진행중",
    featured: true,
  },
  {
    slug: "playhive",
    title: "PlayHive",
    summary: "축구·야구·e스포츠를 주제로 한 클린 스포츠 커뮤니티",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query", "Axios", "DOMPurify"],
    thumbnail: { src: "/projects/PlayHive.png", alt: "PlayHive 이미지" },
    period: "2025.01 - 2025.07",
  },
  {
    slug: "frame",
    title: "Frame",
    summary: "이미지 업로드하고 공유하는 커뮤니티",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query", "Axios", "Supabase"],
    thumbnail: { src: "/projects/Frame.png", alt: "Frame 이미지" },
    period: "2025.04 - 미완성",
  },
  {
    slug: "rolling",
    title: "Rolling",
    summary: "간단한 메시지를 주고받는 롤링페이퍼 서비스",
    techStack: ["React", "Tailwind CSS", "React Query", "Axios"],
    thumbnail: { src: "/projects/Rolling.png", alt: "Rolling 이미지" },
    period: "2025.08 - 2025.08",
  },
  {
    slug: "whyne",
    title: "WHYNE",
    summary: "와인을 등록하고 리뷰를 공유하는 서비스",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Storybook",
      "React Query",
      "Axios",
      "OpenAI-API",
    ],
    thumbnail: { src: "/projects/WHYNE.jpg", alt: "WHYNE 이미지" },
    period: "2025.09 - 2025.10",
  },
  {
    slug: "coworkers",
    title: "Coworkers",
    summary: "팀 협업을 위한 태스크 관리 및 문서 생성 서비스",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Storybook",
      "React Query",
      "Axios",
      "React-pdf",
    ],
    thumbnail: { src: "/projects/Coworkers.png", alt: "Coworkers 이미지" },
    period: "2025.11 - 2025.12",
  },
];
